
#include "6x6_macropad.h"


led_config_t g_led_config = {
//key matrix to LED index
{
    {0,       1,       2,      3,      4,       5},
    {6,       7,       8,      9,      10,       11},
    {12,       13,       14,      15,      16,       17},
    {18,       19,       20,      21,      22,       23},
    {24,       25,       26,      27,      28,       29},
    {30,       31,       32,      33,      34,       35},
},
//LED index to physical position
{
  {1,1},
{1,2},
{1,3},
{1,4},
{1,5},
{1,6},
{2,1},
{2,2},
{2,3},
{2,4},
{2,5},
{2,6},
{3,1},
{3,2},
{3,3},
{3,4},
{3,5},
{3,6},
{4,1},
{4,2},
{4,3},
{4,4},
{4,5},
{4,6},
{5,1},
{5,2},
{5,3},
{5,4},
{5,5},
{5,6},
{6,1},
{6,2},
{6,3},
{6,4},
{6,5},
{6,6}
},
//LED index to flags
{
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT,
  LED_FLAG_KEYLIGHT
  }  
};
